// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgjbfhyrxzmodrmasuvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnamJmaHlyeHptb2RybWFzdXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzA3MjgsImV4cCI6MjA2NTU0NjcyOH0.TRWUZu_dNWUBPm9WXFOX1mUTInHdlWccTiiia-b3Ujk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);